- conda/recipes/ptxcompiler/meta.yaml
Should play it bit nicer with `pip` and other Python packaging tools. Also uses a wheel instead of an egg.
> Use `pip` to do the build & install

- ptxcompiler/_ptxcompilerlib.cpp
This is mostly a cosmetic change, simplifying the code a bit by avoiding creating Python objects from C `unsigned long` variables, instead creating a Python tuple directly from the C variables.
> Avoid multiple Python objects creating tuple from C variables

- ptxcompiler/_ptxcompilerlib.cpp
- ptxcompiler/tests/test_lib.py
Gives more context on the type of error raised by PTX to Python exceptions by parsing error names with strings.
> Parse exceptions with PTX error strings

- ptxcompiler/_ptxcompilerlib.cpp
- ptxcompiler/api.py
- ptxcompiler/tests/test_lib.py
This simplifies `create` API and make it more "Pythonic".
> Leave string length calculation to create's C implementation

- ptxcompiler/_ptxcompilerlib.cpp
When `Py_BuildValue()` returns `null`, an exception is already set (https://docs.python.org/3/c-api/arg.html#c.Py_BuildValue) - setting another exception would seem to obscure the original cause of the failure.
> Don't set a new exception when `Py_BuildValue()` returns `null`

- ptxcompiler/patch.py
This is not ready yet, as it causes odd behaviour in the Numba test suite - the test suite loops round forever, and strange exceptions are observed, e.g.:
```
test_cudajit_in_attached_primary_context (numba.cuda.tests.cudadrv.test_context_stack.Test3rdPartyContext) ... Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/home/gmarkall/miniconda3/envs/numbanp120/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
exitcode = _main(fd, parent_sentinel)
File "/home/gmarkall/miniconda3/envs/numbanp120/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
prepare(preparation_data)
File "/home/gmarkall/miniconda3/envs/numbanp120/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
_fixup_main_from_path(data['init_main_from_path'])
File …
```
> Use subprocess for version check instead of multiprocessing

- setup.py
Needed to fix some compilation issues with the Conda package.
> Use Python prefix for include and library dirs

- ptxcompiler/patch.py
The WSL2 preview driver only accepts PTX up to version 7.4, which is the maximum supported version for CUDA driver 11.4; however, it reports that its version is 11.6. Therefore, on WSL2 we assume a driver "version" of 11.4 so that the Numba patch will be applied if CUDA toolkit 11.5 is used.
cc @shwina @taureandyernv
> Assume driver version 11.4 on WSL2

- ptxcompiler/patch.py
The WSL2 preview driver (which identifies itself as 510.06/ CUDA 11.6) only supported PTX up to version 7.4. However, the latest release driver (496.49) correctly reports the CUDA version it supports (11.5).
Instead of making assumptions about the supported PTX version on WSL based on incorrect behaviour of the preview driver, we should use the reported version as normal, and recommend the use of the latest release driver (and to discontinue use of the preview driver).
This PR also includes some small logging improvements that would have been useful when debugging related issues on WSL2 recently.
After this PR is merged, I think we will need to do another release of ptxcompiler so that WSL2 users don't get the patch erroneously applied.
cc @shwina @taureandyernv @jakirkham
> Undo the assumption of driver version 11.4 on WSL2

- conda/recipes/ptxcompiler/conda_build_config.yaml
Add missing `# [linux]` selector in `conda_build_config.yaml` file
> Add missing selector in conda_build_config.yaml file

- README.md
- ptxcompiler/patch.py
Under some circumstances (usually involving InfiniBand network
stacks), fork() has bad consequences. Introduce environment variables
to control the behaviour of patch_numba_codegen_if_needed (which
previously unconditionally forked a subprocess), to both skip the
check and (optionally) unconditionally patch Numba codegen.
> Allow control of patching via environment variables

- conda/recipes/ptxcompiler/meta.yaml
We removed the `__cuda` metapackage upper bound from the conda-forge recipe in https://github.com/conda-forge/ptxcompiler-feedstock/pull/10. This followed from offline discussions with @quasiben, @gmarkall, and others who agreed it was probably a safe decision and would improve forward compatibility as new CUDA releases are available. This PR applies the same change to this repository.
> Remove __cuda metapackage upper bound.

- ptxcompiler/patch.py
With this change, the `patch_needed()` function can also be used from other libraries without them needing to reimplement the logic and env vars to decide whether to check the driver and runtime versions.
I also updated the message about not patching the Numba codegen - the reason for not patching the codegen is not always the driver version (sometimes it's the environment variable) and the reason should be apparent from previous log lines, so it now only states that the codegen is not being patched.
Some of my experiments/checks with this change (similar to those I did for #20):
```
$ PTXCOMPILER_APPLY_NUMBA_CODEGEN_PATCH=1 NUMBA_CUDA_LOG_LEVEL=DEBUG python -c "from ptxcompiler.patch import patch_numba_codegen_if_needed; patch_numba_codegen_if_needed()"
== CUDA (ptxcompiler) [2612] DEBUG …
```
> Move env var checks into patch_needed() function

- ptxcompiler/patch.py
- ptxcompiler/tests/test_patch.py
I noticed now that https://github.com/conda-forge/ptxcompiler-feedstock/pull/14 is merged, if Numba is not installed then ptxcompiler actually fails to import - this PR remedies this.
Numba should not be a hard dependency of ptxcompiler. This PR modifies patch.py so that it gracefully handles the absence of a supported Numba version.
Added tests:
- Check that patching reports an error when a sufficient version of Numba is not available
- Check the effect of patching when a sufficient version is available.
Fixes #23
> Patch: Make Numba import optional

- ptxcompiler/patch.py
- ptxcompiler/tests/test_patch.py
Changes in #24 turned out to be a step in the right direction but not sufficient to make Numba optional - these additional changes enable the import of ptxcompiler without Numba by adding the following:
- Always defining the required Numba version (needed so that tests can run when Numba is not present)
- Defining `CUDACodeLibrary` when Numba is not present so that the `PTXStaticCompileCodeLibrary` can be defined, though it is not used in this case.
- Immediately returning `False` from `patch_needed()` if Numba is not present, because it cannot be used to check the CUDA version if it is not available.
cc @wence- - apologies for needing this second iteration. I've manually tested this in an environment without Numba too, to make sure that ptxcompiler will import and tests run in that …
> Fix making Numba import optional

- ptxcompiler/patch.py
This refactors `patch.py` such that a consumer of `ptxcompiler` can reuse its machinery for safely checking the CUDA driver version. It also introduces two environment variables `PTXCOMPILER_KNOWN_DRIVER_VERSION` and `PTXCOMPILER_KNOWN_RUNTIME_VERSION` that a user can use to hook into the checking logic and disable unsafe forking if necessary. Finally I also ran `black` on this file.
> Create and expose `safe_get_versions()`

- ptxcompiler/patch.py
Follow up to https://github.com/rapidsai/ptxcompiler/pull/28 fixes a mistake in the logic where nothing was returned if the cuda version checking via subprocess was explicitly disabled.
> Fix `safe_get_versions` logic

- setup.py
For newer compilers the absence of this parameter producing a warning (which is then made into an error by `-Werror`). Specifically, it complains about the usage of nullptr.
> Specify -std=c++11

- README.md
- ptxcompiler/patch.py
- ptxcompiler/tests/test_patch.py
Numba 0.57 should not be patched by ptxcompiler, as its linker already uses ptxcompiler when configured to do so via an environment variable, documented in
https://numba.readthedocs.io/en/stable/cuda/minor_version_compatibility.html.
This prevents ptxcompiler patching these versions of Numba, and advises the use of the environment variable instead.
> Prevent patching of Numba 0.57

- .github/workflows/pr.yaml
- conda/recipes/ptxcompiler/conda_build_config.yaml
- conda/recipes/ptxcompiler/meta.yaml
This PR adds a workflow to build `ptxcompiler` for PRs.
This package is uploaded exclusively to `conda-forge` via https://github.com/conda-forge/ptxcompiler-feedstock/.
Therefore there are no other workflows included besides a PR workflow to ensure that any proposed changes continue to build correctly.
> Add PR build workflow

- .github/workflows/pr.yaml
This PR adds a job to the `pr.yaml` workflow whose sole purpose is to be used as a required job in the repository's branch protection settings.
Using the matrix job as a required job would require updating the branch settings everytime the axis values change.
> Add required job for `pr.yaml`

- conda/recipes/ptxcompiler/meta.yaml
- ptxcompiler/patch.py
We still need the Numba config module even if the Numba version is not OK, so we access it directly from the top-level numba module instead of relying on it being imported following from the version being OK.
This should fix the following exception raised when checking whether to patch and the imported Numba version is 0.57:
```
tests/conftest.py:13: in <module>
import cudf
/opt/conda/envs/test/lib/python3.9/site-packages/cudf/__init__.py:90: in <module>
_setup_numba()
/opt/conda/envs/test/lib/python3.9/site-packages/cudf/utils/_numba.py:123: in _setup_numba
versions = safe_get_versions()
/opt/conda/envs/test/lib/python3.9/site-packages/ptxcompiler/patch.py:234: in safe_get_versions
if check_disabled_in_env():
/opt/conda/envs/test/lib/python3.9/site-packages/ptxcompiler/patch.py:166: in …
```
> Don't rely on the Numba version to be OK for config

- .github/workflows/pr.yaml
These are now equivalent in behavior. However support for `conda-mambabuild` is being dropped. So switch to `conda-build`.
xref: https://github.com/rapidsai/build-planning/issues/149
> Replace `conda-mambabuild` with `conda-build`
